name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0 # Match your .NET version

    # Step 3: Restore Dependencies
    - name: Restore dependencies
      run: dotnet restore ./src/Backend

    # Step 4: Build the Project
    - name: Build project
      run: dotnet build ./src/Backend --no-restore --configuration Release

    # Step 5: Run Unit Tests (if applicable)
    - name: Run tests
      run: dotnet test ./src/Backend --no-build --verbosity normal

    # Step 6: Publish the Application
    - name: Publish artifacts
      run: dotnet publish ./src/Backend --no-build --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Upload Artifacts to AWS S3 (optional static assets)
    - name: Upload to S3
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        aws s3 sync ./publish s3://your-s3-bucket-name --acl public-read

    # Step 3: Deploy to AWS EC2
    - name: Deploy to EC2
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        scp -i your-key.pem -r ./publish ec2-user@your-ec2-public-ip:/var/www/wms-backend
        ssh -i your-key.pem ec2-user@your-ec2-public-ip "sudo systemctl restart wms-backend.service"
